### ISSUE TITLE
trokes.org has expired

### ISSUE THREAD

**Issue by eggsyntax** [dribnet/strokes#15]
& so example links on front page end up at:

"This domain may be for sale. Backorder this Domain
This Domain Name Has Expired - Renewal Instructions."

**Comment by dribnet** [comment]
Thanks, I'll look into this! In the meantime, you can simply replace the s.trokes.org part of the URL with bl.ocks.org since strokes was just a clone of blocks with clojure syntax highlighting enabled.

**Comment by eggsyntax** [comment]
Thanks, that's really helpful!

**Comment by dribnet** [comment]
All s.trokes.org links can now be accessed via bl.ocks.org instead.
